name: Build Windows Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install

      - name: Install deps
        run: |
          vcpkg/vcpkg install openssl:x64-windows opus:x64-windows paho-mqttpp3:x64-windows

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          arch: win64_msvc2019_64
          modules: 'qtmultimedia qtwebsockets'

      - name: Configure
        run: |
          cmake -B build -S . -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_TOOLCHAIN_FILE=%CD%/vcpkg/scripts/buildsystems/vcpkg.cmake ^
            -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: cmake --build build --config Release
